trigger: none
name: $(date:yyyyMMdd)$(rev:.r)

variables:
- group: 'F5_dmz'
- group: 'IIS'
- group: 'modelo_core_mvc'

stages:
- stage: build
  displayName: 'Criação dos artefatos'
  jobs:
  - job:
    pool:
      name: Visual Studio
    steps:
    - checkout: self
    - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}:
      - task: SonarQubePrepare@4
        displayName: Prepare analysis on SonarQube
        continueOnError: True
        inputs:
          SonarQube: 86a0aeb0-42e0-4aeb-bb38-c46e0b00b615
          projectKey: Layout_Padrao_modelo_core_mvc_AYICN6jAipiVWg4CBkqP
          projectName: modelo_core_mvc
          extraProperties: "# Additional properties that will be passed to the scanner, \n# Put one key=value per line, example:\nsonar.exclusions=**/wwwroot/**, **/docker/**"
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(projects)
        selectOrConfig: config
        feedRestore: 4eb34145-aff0-41ad-a936-1f3645390db5
        nugetConfigPath: D:\Nuget\nuget.config
        noCache: true
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: $(projects)
        arguments: '--configuration $(BuildConfiguration) --no-restore '
    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: test
        projects: '**/*[Tt]ests/*.csproj'
        arguments: --configuration $(BuildConfiguration)
    - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}:
      - task: SonarQubeAnalyze@4
        displayName: Run Code Analysis
        continueOnError: True
      - task: SonarQubePublish@4
        displayName: Publish Quality Gate Result
        continueOnError: True
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        projects: $(projects)
        arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --no-build --no-restore
        zipAfterPublish: True
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Dev
  displayName: 'Deploy Dev'
  dependsOn: build
  variables:
  - group: 'DEV'
  jobs:
  - deployment: IIS
    variables:
    - name: '_Web_Site_Nome'
      value: 'Seguro'
    environment: 
      name: envPadroesDesenvolvimento
      resourceName: SRV72208
    strategy: 
      runOnce:
        deploy:
          steps:
          - download: current
            env:
              NODE_TLS_REJECT_UNAUTHORIZED: 0
            artifact: drop
            patterns: '**/*.zip'
            displayName: 'Download artefatos'
          - task: IISWebAppManagementOnMachineGroup@0
            displayName: 'IIS Web App Manage'
            inputs:
              IISDeploymentType: 'IISWebApplication'
              WebsiteName: '$(_Web_Site_Nome)'
              ParentWebsiteNameForVD: '$(_Web_Site_Nome)'
              VirtualPathForVD: '/$(_Nome_Aplicacao)'
              ParentWebsiteNameForApplication: '$(_Web_Site_Nome)'
              VirtualPathForApplication: '/$(_Nome_Aplicacao)'
              PhysicalPathForApplication: '$(_Local_IIS)\$(_Web_Site_Local)\$(_Nome_Aplicacao)'
              AddBinding: true
              Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"8088","hostname":"","sslThumbprint":"","sniFlag":false}]}'
              CreateOrUpdateAppPoolForApplication: true
              AppPoolNameForApplication: '$(_Nome_Aplicacao)'
              DotNetVersionForApplication: 'No Managed Code'
              AppPoolName: '$(_Nome_Aplicacao)'
              AppPoolNameForWebsite: '$(_Nome_Aplicacao)'
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: '$(_Web_Site_Nome)'
              VirtualApplication: '$(_Nome_Aplicacao)'
              Package: '$(_drop).zip'
              RemoveAdditionalFilesFlag: true
              ExcludeFilesFromAppDataFlag: true
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true
              JSONFiles: 'appsettings.json'
          - powershell: |
                  Write-Host "_________________________________________________________________ "
                  Write-Host "appsettings"
                  Write-Host ""
                  type $(_Local_IIS)\$(_Web_Site_Local)\$(_Nome_Aplicacao)\appsettings.json
                  
                  Write-Host "_________________________________________________________________ "
                  Write-Host "web.config"
                  Write-Host ""
                  type $(_Local_IIS)\$(_Web_Site_Local)\$(_Nome_Aplicacao)\web.config
                  
                  Write-Host "_________________________________________________________________ "
                  Write-Host "Dir $(_Local_IIS)\$(_Web_Site_Local)\$(_Nome_Aplicacao)"
                  Write-Host ""
                  Get-ChildItem -Path $(_Local_IIS)\$(_Web_Site_Local)\$(_Nome_Aplicacao)
                  
                  Write-Host "_________________________________________________________________ "
                  Write-Host "Dir $(_Local_IIS)\$(_Web_Site_Local)\$(_Nome_Aplicacao)\wwwroot\img"
                  Write-Host ""
                  Get-ChildItem -Path $(_Local_IIS)\$(_Web_Site_Local)\$(_Nome_Aplicacao)\wwwroot\img
            displayName: 'Verificação do arquivo de configuração'
