variables:
  BuildParameters.RestoreBuildProjects: '**/*modelo_core_mvc.csproj'
  buildConfiguration: release
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job:
  pool:
    name: Visual Studio
  steps:
  - checkout: self
  - task: SonarQubePrepare@4
    displayName: Prepare analysis on SonarQube
    continueOnError: True
    inputs:
      SonarQube: 86a0aeb0-42e0-4aeb-bb38-c46e0b00b615
      projectKey: Layout_Padrao_modelo_core_mvc_AYICN6jAipiVWg4CBkqP
      projectName: modelo_core_mvc
      extraProperties: "# Additional properties that will be passed to the scanner, \n# Put one key=value per line, example:\nsonar.exclusions=**/wwwroot/**, **/docker/**"
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
      selectOrConfig: config
      feedRestore: 4eb34145-aff0-41ad-a936-1f3645390db5
      nugetConfigPath: D:\Nuget\nuget.config
      noCache: true
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: '--configuration $(BuildConfiguration) --no-restore '
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: '**/*[Tt]ests/*.csproj'
      arguments: --configuration $(BuildConfiguration)
  - task: SonarQubeAnalyze@4
    displayName: Run Code Analysis
    continueOnError: True
  - task: SonarQubePublish@4
    displayName: Publish Quality Gate Result
    continueOnError: True
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --no-build --no-restore
      zipAfterPublish: True
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'

