jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Visual Studio
  steps:
  variables:
    _Local_IIS: 'D:\inetpub'
    _Web_Site_Local: 'secure'
    _Nome_Aplicacao: 'modelo_core_mvc'

  - task: IISWebAppManagementOnMachineGroup@0
    displayName: 'IIS Web App Manage'
    inputs:
      IISDeploymentType: '$(Parameters.IISDeploymentType)'
      WebsiteName: '$(Parameters.WebsiteName)'
      AddBinding: '$(Parameters.AddBinding)'
      Bindings: '$(Parameters.Bindings)'
      ParentWebsiteNameForVD: '$(Parameters.WebsiteName)'
      VirtualPathForVD: '$(Parameters.VirtualPathForApplication)'
      ParentWebsiteNameForApplication: '$(Parameters.WebsiteName)'
      VirtualPathForApplication: '$(Parameters.VirtualPathForApplication)'
      PhysicalPathForApplication: '$(_Local_IIS)\$(_Web_Site_Local)\$(_Nome_Aplicacao)'
      CreateOrUpdateAppPoolForApplication: true
      AppPoolNameForApplication: '$(_Nome_Aplicacao)'
      DotNetVersionForApplication: 'No Managed Code'
      AppPoolName: '$(Parameters.AppPoolName)'
  