trigger: none

resources:
  pipelines:
    - pipeline: build
      source: Backend/Classic/AZ400-Backend-Package
      project: AZ400-DevOps

jobs:
- deployment: DeployWeb
  environment: 'development'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self 
        - download: build
          artifact: drop
        - task: IISWebAppManagementOnMachineGroup@0
          displayName: 'IIS Web App Manage'
          inputs:
            EnableIIS: true
            IISDeploymentType: 'IISWebsite'
            ActionIISWebsite: 'CreateOrUpdateWebsite'
            WebsiteName: 'AZ400-Backend'
            WebsitePhysicalPath: 'c:\temp\AZ400-Backend'
            WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
            AddBinding: true
            Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"8088","hostname":"","sslThumbprint":"","sniFlag":false}]}'
            CreateOrUpdateAppPoolForWebsite: true
            AppPoolNameForWebsite: 'AZ400-Backend'
            DotNetVersionForWebsite: 'No Managed Code'
            PipeLineModeForWebsite: 'Integrated'
            AppPoolIdentityForWebsite: 'SpecificUser'
            AppPoolUsernameForWebsite: 'vmadmin'
            AppPoolPasswordForWebsite: '$(apppool-password)'

        - task: IISWebAppDeploymentOnMachineGroup@0
          displayName: 'IIS Web App Deploy'
          inputs:
            WebSiteName: 'AZ400-Backend'
            Package: '$(Pipeline.Workspace)\build\drop\*.zip'
            TakeAppOfflineFlag: true
            JSONFiles: 'appsettings.json'

        - task: Tokenizer@2
          displayName: 'Tokenizer: Transform Source filename'
          inputs:
            SourcePath: 'c:\temp\AZ400-Backend\appsettings.json'
            DestinationPath: 'appsettings.json'
          enabled: true



#trigger: none
#
#resources:
#  pipelines:
#    - pipeline: build
#      source: Backend/Classic/AZ400-Backend-Package
#      project: AZ400-DevOps
#
#pool:
#  name: Default
#  demands: Agent.Name -equals LabVM
#
#steps:
#- download: build
#  artifact: drop
#- task: IISWebAppManagementOnMachineGroup@0
#  displayName: 'IIS Web App Manage'
#  inputs:
#    EnableIIS: true
#    IISDeploymentType: 'IISWebsite'
#    ActionIISWebsite: 'CreateOrUpdateWebsite'
#    WebsiteName: 'AZ400-Backend'
#    WebsitePhysicalPath: 'c:\temp\AZ400-Backend'
#    WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
#    AddBinding: true
#    Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"8088","hostname":"","sslThumbprint":"","sniFlag":false}]}'
#    CreateOrUpdateAppPoolForWebsite: true
#    AppPoolNameForWebsite: 'AZ400-Backend'
#    DotNetVersionForWebsite: 'No Managed Code'
#    PipeLineModeForWebsite: 'Integrated'
#    AppPoolIdentityForWebsite: 'SpecificUser'
#    AppPoolUsernameForWebsite: 'vmadmin'
#    AppPoolPasswordForWebsite: '$(apppool-password)'
#
#- task: IISWebAppDeploymentOnMachineGroup@0
#  displayName: 'IIS Web App Deploy'
#  inputs:
#    WebSiteName: 'AZ400-Backend'
#    Package: '$(Pipeline.Workspace)\build\drop\*.zip'
#    TakeAppOfflineFlag: true
#    JSONFiles: 'appsettings.json'
#
#- task: Tokenizer@2
#  displayName: 'Tokenizer: Transform Source filename'
#  inputs:
#    SourcePath: 'c:\temp\AZ400-Backend\appsettings.json'
#    DestinationPath: 'appsettings.json'
#  enabled: true